"""Second migrations

Revision ID: cd95ac11fd86
Revises: 
Create Date: 2025-03-26 09:38:47.146182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd95ac11fd86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulledmoney',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('totalMoney', sa.Integer(), nullable=False),
    sa.Column('pulledmoney', sa.Float(), nullable=False),
    sa.Column('totalLeft', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulledmoney')
    # ### end Alembic commands ###
